CREATE TABLE MENSAJES_HEX (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    MENSAJE_ENVIO CLOB,
    MENSAJE_RESPUESTA CLOB,
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMIT;

SELECT * FROM MENSAJES_HEX;git 